services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"
    environment:
      - HOST=0.0.0.0
